[project]
name = "hexlet-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Natchlazen", email = "gempro760@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dj-database-url>=3.1.2",
    "django>=6.1",
    "django-bootstrap5>=26.2",
    "django-filter>=26.1",
    "django-filter>=26.1",
    "gunicorn>=26.1.0",
    "psycopg[binary]>=3.2.0",
    "python-dotenv>=1.2.3",
    "sentry-sdk[django]>=2.68.0",
]

[project.scripts]
python-project-208 = "hexlet_code:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "coverage>=7.0",
    "pytest>=8.0",
    "pytest-django>=4.0",
    "ruff>=0.16.4",
]

[tool.ruff]
exclude = ["migrations", "settings.py"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "task_manager.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
